/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AcessTokenDTO
 */
export interface AcessTokenDTO {
    /**
     * JWT Access token
     * @type {string}
     * @memberof AcessTokenDTO
     */
    accessToken: string;
}

/**
 * Check if a given object implements the AcessTokenDTO interface.
 */
export function instanceOfAcessTokenDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'accessToken' in value;

    return isInstance;
}

export function AcessTokenDTOFromJSON(json: any): AcessTokenDTO {
    return AcessTokenDTOFromJSONTyped(json, false);
}

export function AcessTokenDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AcessTokenDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        accessToken: json['access_token']
    };
}

export function AcessTokenDTOToJSON(value?: AcessTokenDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        access_token: value.accessToken
    };
}
