/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AttachmentSubmissionDTO
 */
export interface AttachmentSubmissionDTO {
    /**
     * The name of the attachment
     * @type {string}
     * @memberof AttachmentSubmissionDTO
     */
    name: string;
    /**
     * The url of the attachment
     * @type {string}
     * @memberof AttachmentSubmissionDTO
     */
    url: string;
}

/**
 * Check if a given object implements the AttachmentSubmissionDTO interface.
 */
export function instanceOfAttachmentSubmissionDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'name' in value;
    isInstance = isInstance && 'url' in value;

    return isInstance;
}

export function AttachmentSubmissionDTOFromJSON(json: any): AttachmentSubmissionDTO {
    return AttachmentSubmissionDTOFromJSONTyped(json, false);
}

export function AttachmentSubmissionDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AttachmentSubmissionDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: json['name'],
        url: json['url']
    };
}

export function AttachmentSubmissionDTOToJSON(
    value?: AttachmentSubmissionDTO | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
        url: value.url
    };
}
