/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type CourseDTOGeneralObjective
 * Course general objective
 * @export
 */
export type CourseDTOGeneralObjective = Null | string;

export function CourseDTOGeneralObjectiveFromJSON(json: any): CourseDTOGeneralObjective {
    return CourseDTOGeneralObjectiveFromJSONTyped(json, false);
}

export function CourseDTOGeneralObjectiveFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CourseDTOGeneralObjective {
    if (json === undefined || json === null) {
        return json;
    }
    return { ...NullFromJSONTyped(json, true), ...stringFromJSONTyped(json, true) };
}

export function CourseDTOGeneralObjectiveToJSON(
    value?: CourseDTOGeneralObjective | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfNull(value)) {
        return NullToJSON(value as Null);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}
