/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CourseEntity
 */
export interface CourseEntity {
    /**
     * Course id
     * @type {string}
     * @memberof CourseEntity
     */
    id: string;
    /**
     * Course name
     * @type {string}
     * @memberof CourseEntity
     */
    name: string;
    /**
     * Group id
     * @type {string}
     * @memberof CourseEntity
     */
    groupId: string;
    /**
     * Teacher id
     * @type {string}
     * @memberof CourseEntity
     */
    teacherId: string;
}

/**
 * Check if a given object implements the CourseEntity interface.
 */
export function instanceOfCourseEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'name' in value;
    isInstance = isInstance && 'groupId' in value;
    isInstance = isInstance && 'teacherId' in value;

    return isInstance;
}

export function CourseEntityFromJSON(json: any): CourseEntity {
    return CourseEntityFromJSONTyped(json, false);
}

export function CourseEntityFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CourseEntity {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json['id'],
        name: json['name'],
        groupId: json['groupId'],
        teacherId: json['teacherId']
    };
}

export function CourseEntityToJSON(value?: CourseEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        name: value.name,
        groupId: value.groupId,
        teacherId: value.teacherId
    };
}
