/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Teacher
 * @export
 * @interface CourseEntityTeacher
 */
export interface CourseEntityTeacher {
    /**
     * Teacher id
     * @type {string}
     * @memberof CourseEntityTeacher
     */
    id: string;
    /**
     * Teacher email
     * @type {string}
     * @memberof CourseEntityTeacher
     */
    email: string;
}

/**
 * Check if a given object implements the CourseEntityTeacher interface.
 */
export function instanceOfCourseEntityTeacher(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'email' in value;

    return isInstance;
}

export function CourseEntityTeacherFromJSON(json: any): CourseEntityTeacher {
    return CourseEntityTeacherFromJSONTyped(json, false);
}

export function CourseEntityTeacherFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CourseEntityTeacher {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json['id'],
        email: json['email']
    };
}

export function CourseEntityTeacherToJSON(value?: CourseEntityTeacher | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        email: value.email
    };
}
