/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CourseDTO
 */
export interface CourseDTO {
    /**
     * Course id
     * @type {string}
     * @memberof CourseDTO
     */
    id: string;
    /**
     * Course name
     * @type {string}
     * @memberof CourseDTO
     */
    name: string;
    /**
     * Teacher data
     * @type {object}
     * @memberof CourseDTO
     */
    teacher: object;
}

/**
 * Check if a given object implements the CourseDTO interface.
 */
export function instanceOfCourseDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'name' in value;
    isInstance = isInstance && 'teacher' in value;

    return isInstance;
}

export function CourseDTOFromJSON(json: any): CourseDTO {
    return CourseDTOFromJSONTyped(json, false);
}

export function CourseDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CourseDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json['id'],
        name: json['name'],
        teacher: json['teacher']
    };
}

export function CourseDTOToJSON(value?: CourseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        name: value.name,
        teacher: value.teacher
    };
}
