/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Teacher data
 * @export
 * @interface CourseDTOTeacher
 */
export interface CourseDTOTeacher {
    /**
     * Teacher first name
     * @type {string}
     * @memberof CourseDTOTeacher
     */
    firstName: string;
    /**
     * Teacher last name
     * @type {string}
     * @memberof CourseDTOTeacher
     */
    lastName: string;
}

/**
 * Check if a given object implements the CourseDTOTeacher interface.
 */
export function instanceOfCourseDTOTeacher(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'firstName' in value;
    isInstance = isInstance && 'lastName' in value;

    return isInstance;
}

export function CourseDTOTeacherFromJSON(json: any): CourseDTOTeacher {
    return CourseDTOTeacherFromJSONTyped(json, false);
}

export function CourseDTOTeacherFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CourseDTOTeacher {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        firstName: json['firstName'],
        lastName: json['lastName']
    };
}

export function CourseDTOTeacherToJSON(value?: CourseDTOTeacher | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        firstName: value.firstName,
        lastName: value.lastName
    };
}
