/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface JWTPayload
 */
export interface JWTPayload {
    /**
     * User email
     * @type {string}
     * @memberof JWTPayload
     */
    email: string;
    /**
     * User id
     * @type {string}
     * @memberof JWTPayload
     */
    id: string;
    /**
     * User role
     * @type {string}
     * @memberof JWTPayload
     */
    role: string;
}

/**
 * Check if a given object implements the JWTPayload interface.
 */
export function instanceOfJWTPayload(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'email' in value;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'role' in value;

    return isInstance;
}

export function JWTPayloadFromJSON(json: any): JWTPayload {
    return JWTPayloadFromJSONTyped(json, false);
}

export function JWTPayloadFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): JWTPayload {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        email: json['email'],
        id: json['id'],
        role: json['role']
    };
}

export function JWTPayloadToJSON(value?: JWTPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        email: value.email,
        id: value.id,
        role: value.role
    };
}
