/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RegisterStudentDTO
 */
export interface RegisterStudentDTO {
    /**
     * Student id
     * @type {string}
     * @memberof RegisterStudentDTO
     */
    id: string;
    /**
     * Student email
     * @type {string}
     * @memberof RegisterStudentDTO
     */
    email: string;
    /**
     * Student first name
     * @type {string}
     * @memberof RegisterStudentDTO
     */
    firstName: string;
    /**
     * Student last name
     * @type {string}
     * @memberof RegisterStudentDTO
     */
    lastName: string;
    /**
     * Student career id
     * @type {number}
     * @memberof RegisterStudentDTO
     */
    careerId: number;
    /**
     * Student password
     * @type {string}
     * @memberof RegisterStudentDTO
     */
    password: string;
}

/**
 * Check if a given object implements the RegisterStudentDTO interface.
 */
export function instanceOfRegisterStudentDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'email' in value;
    isInstance = isInstance && 'firstName' in value;
    isInstance = isInstance && 'lastName' in value;
    isInstance = isInstance && 'careerId' in value;
    isInstance = isInstance && 'password' in value;

    return isInstance;
}

export function RegisterStudentDTOFromJSON(json: any): RegisterStudentDTO {
    return RegisterStudentDTOFromJSONTyped(json, false);
}

export function RegisterStudentDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): RegisterStudentDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json['id'],
        email: json['email'],
        firstName: json['firstName'],
        lastName: json['lastName'],
        careerId: json['careerId'],
        password: json['password']
    };
}

export function RegisterStudentDTOToJSON(value?: RegisterStudentDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        email: value.email,
        firstName: value.firstName,
        lastName: value.lastName,
        careerId: value.careerId,
        password: value.password
    };
}
