/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RegisterStudentDTO
 */
export interface RegisterStudentDTO {
    /**
     * User email
     * @type {string}
     * @memberof RegisterStudentDTO
     */
    email: string;
    /**
     * User password
     * @type {string}
     * @memberof RegisterStudentDTO
     */
    password: string;
    /**
     * User first name
     * @type {string}
     * @memberof RegisterStudentDTO
     */
    firstName: string;
    /**
     * User last name
     * @type {string}
     * @memberof RegisterStudentDTO
     */
    lastName: string;
    /**
     * User career id
     * @type {number}
     * @memberof RegisterStudentDTO
     */
    careerId: number;
    /**
     * User role
     * @type {string}
     * @memberof RegisterStudentDTO
     */
    role: RegisterStudentDTORoleEnum;
    /**
     * User student id
     * @type {string}
     * @memberof RegisterStudentDTO
     */
    id: string;
}

/**
 * @export
 */
export const RegisterStudentDTORoleEnum = {
    Admin: 'ADMIN',
    Teacher: 'TEACHER',
    Student: 'STUDENT'
} as const;
export type RegisterStudentDTORoleEnum =
    (typeof RegisterStudentDTORoleEnum)[keyof typeof RegisterStudentDTORoleEnum];

/**
 * Check if a given object implements the RegisterStudentDTO interface.
 */
export function instanceOfRegisterStudentDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'email' in value;
    isInstance = isInstance && 'password' in value;
    isInstance = isInstance && 'firstName' in value;
    isInstance = isInstance && 'lastName' in value;
    isInstance = isInstance && 'careerId' in value;
    isInstance = isInstance && 'role' in value;
    isInstance = isInstance && 'id' in value;

    return isInstance;
}

export function RegisterStudentDTOFromJSON(json: any): RegisterStudentDTO {
    return RegisterStudentDTOFromJSONTyped(json, false);
}

export function RegisterStudentDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): RegisterStudentDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        email: json['email'],
        password: json['password'],
        firstName: json['firstName'],
        lastName: json['lastName'],
        careerId: json['careerId'],
        role: json['role'],
        id: json['id']
    };
}

export function RegisterStudentDTOToJSON(value?: RegisterStudentDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        email: value.email,
        password: value.password,
        firstName: value.firstName,
        lastName: value.lastName,
        careerId: value.careerId,
        role: value.role,
        id: value.id
    };
}
