/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Teacher who qualified the submission
 * @export
 * @interface StudentSubmissionDTOTeacher
 */
export interface StudentSubmissionDTOTeacher {
    /**
     * Teacher first name
     * @type {string}
     * @memberof StudentSubmissionDTOTeacher
     */
    firstName: string;
    /**
     * Teacher last name
     * @type {string}
     * @memberof StudentSubmissionDTOTeacher
     */
    lastName: string;
}

/**
 * Check if a given object implements the StudentSubmissionDTOTeacher interface.
 */
export function instanceOfStudentSubmissionDTOTeacher(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'firstName' in value;
    isInstance = isInstance && 'lastName' in value;

    return isInstance;
}

export function StudentSubmissionDTOTeacherFromJSON(
    json: any
): StudentSubmissionDTOTeacher {
    return StudentSubmissionDTOTeacherFromJSONTyped(json, false);
}

export function StudentSubmissionDTOTeacherFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): StudentSubmissionDTOTeacher {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        firstName: json['firstName'],
        lastName: json['lastName']
    };
}

export function StudentSubmissionDTOTeacherToJSON(
    value?: StudentSubmissionDTOTeacher | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        firstName: value.firstName,
        lastName: value.lastName
    };
}
