/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StudentDTOGroup } from './StudentDTOGroup';
import {
    StudentDTOGroupFromJSON,
    StudentDTOGroupFromJSONTyped,
    StudentDTOGroupToJSON
} from './StudentDTOGroup';

/**
 *
 * @export
 * @interface StudentDTO
 */
export interface StudentDTO {
    /**
     * Student id
     * @type {string}
     * @memberof StudentDTO
     */
    id: string;
    /**
     * Student email
     * @type {string}
     * @memberof StudentDTO
     */
    email: string;
    /**
     * Student first name
     * @type {string}
     * @memberof StudentDTO
     */
    firstName: string;
    /**
     * Student last name
     * @type {string}
     * @memberof StudentDTO
     */
    lastName: string;
    /**
     * Student role
     * @type {string}
     * @memberof StudentDTO
     */
    role: StudentDTORoleEnum;
    /**
     * Student description
     * @type {string}
     * @memberof StudentDTO
     */
    description: string | null;
    /**
     * Student description
     * @type {string}
     * @memberof StudentDTO
     */
    city: string | null;
    /**
     * Student avatar
     * @type {string}
     * @memberof StudentDTO
     */
    avatar: string;
    /**
     * Student career data
     * @type {object}
     * @memberof StudentDTO
     */
    career: object;
    /**
     *
     * @type {StudentDTOGroup}
     * @memberof StudentDTO
     */
    group: StudentDTOGroup;
}

/**
 * @export
 */
export const StudentDTORoleEnum = {
    Student: 'STUDENT',
    Teacher: 'TEACHER'
} as const;
export type StudentDTORoleEnum =
    (typeof StudentDTORoleEnum)[keyof typeof StudentDTORoleEnum];

/**
 * Check if a given object implements the StudentDTO interface.
 */
export function instanceOfStudentDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'email' in value;
    isInstance = isInstance && 'firstName' in value;
    isInstance = isInstance && 'lastName' in value;
    isInstance = isInstance && 'role' in value;
    isInstance = isInstance && 'description' in value;
    isInstance = isInstance && 'city' in value;
    isInstance = isInstance && 'avatar' in value;
    isInstance = isInstance && 'career' in value;
    isInstance = isInstance && 'group' in value;

    return isInstance;
}

export function StudentDTOFromJSON(json: any): StudentDTO {
    return StudentDTOFromJSONTyped(json, false);
}

export function StudentDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): StudentDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json['id'],
        email: json['email'],
        firstName: json['firstName'],
        lastName: json['lastName'],
        role: json['role'],
        description: json['description'],
        city: json['city'],
        avatar: json['avatar'],
        career: json['career'],
        group: StudentDTOGroupFromJSON(json['group'])
    };
}

export function StudentDTOToJSON(value?: StudentDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        email: value.email,
        firstName: value.firstName,
        lastName: value.lastName,
        role: value.role,
        description: value.description,
        city: value.city,
        avatar: value.avatar,
        career: value.career,
        group: StudentDTOGroupToJSON(value.group)
    };
}
