/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface StudentInGroup
 */
export interface StudentInGroup {
    /**
     * Student id
     * @type {string}
     * @memberof StudentInGroup
     */
    id: string;
    /**
     * Student email
     * @type {string}
     * @memberof StudentInGroup
     */
    email: string;
}

/**
 * Check if a given object implements the StudentInGroup interface.
 */
export function instanceOfStudentInGroup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'email' in value;

    return isInstance;
}

export function StudentInGroupFromJSON(json: any): StudentInGroup {
    return StudentInGroupFromJSONTyped(json, false);
}

export function StudentInGroupFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): StudentInGroup {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json['id'],
        email: json['email']
    };
}

export function StudentInGroupToJSON(value?: StudentInGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        email: value.email
    };
}
