/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TaskInCourse
 */
export interface TaskInCourse {
    /**
     * The id of the task
     * @type {number}
     * @memberof TaskInCourse
     */
    id: number;
    /**
     * The title of the task
     * @type {string}
     * @memberof TaskInCourse
     */
    title: string;
    /**
     * The due date of the task
     * @type {string}
     * @memberof TaskInCourse
     */
    dueDate: string;
}

/**
 * Check if a given object implements the TaskInCourse interface.
 */
export function instanceOfTaskInCourse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'title' in value;
    isInstance = isInstance && 'dueDate' in value;

    return isInstance;
}

export function TaskInCourseFromJSON(json: any): TaskInCourse {
    return TaskInCourseFromJSONTyped(json, false);
}

export function TaskInCourseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TaskInCourse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json['id'],
        title: json['title'],
        dueDate: json['dueDate']
    };
}

export function TaskInCourseToJSON(value?: TaskInCourse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        title: value.title,
        dueDate: value.dueDate
    };
}
