/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TeacherCourses
 */
export interface TeacherCourses {
    /**
     * Course id
     * @type {string}
     * @memberof TeacherCourses
     */
    id: string;
    /**
     * Course name
     * @type {string}
     * @memberof TeacherCourses
     */
    name: string;
    /**
     * Teacher id
     * @type {string}
     * @memberof TeacherCourses
     */
    teacherId: string;
}

/**
 * Check if a given object implements the TeacherCourses interface.
 */
export function instanceOfTeacherCourses(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'name' in value;
    isInstance = isInstance && 'teacherId' in value;

    return isInstance;
}

export function TeacherCoursesFromJSON(json: any): TeacherCourses {
    return TeacherCoursesFromJSONTyped(json, false);
}

export function TeacherCoursesFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TeacherCourses {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json['id'],
        name: json['name'],
        teacherId: json['teacherId']
    };
}

export function TeacherCoursesToJSON(value?: TeacherCourses | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        name: value.name,
        teacherId: value.teacherId
    };
}
