/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TeacherInCourse
 */
export interface TeacherInCourse {
    /**
     * Teacher first name
     * @type {string}
     * @memberof TeacherInCourse
     */
    firstName: string;
    /**
     * Teacher last name
     * @type {string}
     * @memberof TeacherInCourse
     */
    lastName: string;
}

/**
 * Check if a given object implements the TeacherInCourse interface.
 */
export function instanceOfTeacherInCourse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'firstName' in value;
    isInstance = isInstance && 'lastName' in value;

    return isInstance;
}

export function TeacherInCourseFromJSON(json: any): TeacherInCourse {
    return TeacherInCourseFromJSONTyped(json, false);
}

export function TeacherInCourseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TeacherInCourse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        firstName: json['firstName'],
        lastName: json['lastName']
    };
}

export function TeacherInCourseToJSON(value?: TeacherInCourse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        firstName: value.firstName,
        lastName: value.lastName
    };
}
