/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateCourseDTO
 */
export interface UpdateCourseDTO {
    /**
     * Course id
     * @type {string}
     * @memberof UpdateCourseDTO
     */
    courseId?: string;
    /**
     * Course name
     * @type {string}
     * @memberof UpdateCourseDTO
     */
    name?: string;
    /**
     * Course instructor id
     * @type {string}
     * @memberof UpdateCourseDTO
     */
    teacherId?: string;
}

/**
 * Check if a given object implements the UpdateCourseDTO interface.
 */
export function instanceOfUpdateCourseDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateCourseDTOFromJSON(json: any): UpdateCourseDTO {
    return UpdateCourseDTOFromJSONTyped(json, false);
}

export function UpdateCourseDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): UpdateCourseDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        courseId: !exists(json, 'courseId') ? undefined : json['courseId'],
        name: !exists(json, 'name') ? undefined : json['name'],
        teacherId: !exists(json, 'teacherId') ? undefined : json['teacherId']
    };
}

export function UpdateCourseDTOToJSON(value?: UpdateCourseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        courseId: value.courseId,
        name: value.name,
        teacherId: value.teacherId
    };
}
