/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateSubmissionDTO
 */
export interface UpdateSubmissionDTO {
    /**
     * Comment for the submission
     * @type {string}
     * @memberof UpdateSubmissionDTO
     */
    comment?: string;
}

/**
 * Check if a given object implements the UpdateSubmissionDTO interface.
 */
export function instanceOfUpdateSubmissionDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateSubmissionDTOFromJSON(json: any): UpdateSubmissionDTO {
    return UpdateSubmissionDTOFromJSONTyped(json, false);
}

export function UpdateSubmissionDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): UpdateSubmissionDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        comment: !exists(json, 'comment') ? undefined : json['comment']
    };
}

export function UpdateSubmissionDTOToJSON(value?: UpdateSubmissionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        comment: value.comment
    };
}
