/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { RegisterStudentDTO, StudentDTO } from '../models';
import {
    RegisterStudentDTOFromJSON,
    RegisterStudentDTOToJSON,
    StudentDTOFromJSON,
    StudentDTOToJSON
} from '../models';

export interface StudentControllerRegisterStudentRequest {
    registerStudentDTO: RegisterStudentDTO;
}

/**
 * StudentApi - interface
 *
 * @export
 * @interface StudentApiInterface
 */
export interface StudentApiInterface {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StudentApiInterface
     */
    studentControllerGetMeRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<StudentDTO>>;

    /**
     */
    studentControllerGetMe(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<StudentDTO>;

    /**
     *
     * @param {RegisterStudentDTO} registerStudentDTO
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StudentApiInterface
     */
    studentControllerRegisterStudentRaw(
        requestParameters: StudentControllerRegisterStudentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<StudentDTO>>;

    /**
     */
    studentControllerRegisterStudent(
        requestParameters: StudentControllerRegisterStudentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<StudentDTO>;
}

/**
 *
 */
export class StudentApi extends runtime.BaseAPI implements StudentApiInterface {
    /**
     */
    async studentControllerGetMeRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<StudentDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/student/me`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            StudentDTOFromJSON(jsonValue)
        );
    }

    /**
     */
    async studentControllerGetMe(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<StudentDTO> {
        const response = await this.studentControllerGetMeRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async studentControllerRegisterStudentRaw(
        requestParameters: StudentControllerRegisterStudentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<StudentDTO>> {
        if (
            requestParameters.registerStudentDTO === null ||
            requestParameters.registerStudentDTO === undefined
        ) {
            throw new runtime.RequiredError(
                'registerStudentDTO',
                'Required parameter requestParameters.registerStudentDTO was null or undefined when calling studentControllerRegisterStudent.'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request(
            {
                path: `/api/student/create`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: RegisterStudentDTOToJSON(requestParameters.registerStudentDTO)
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            StudentDTOFromJSON(jsonValue)
        );
    }

    /**
     */
    async studentControllerRegisterStudent(
        requestParameters: StudentControllerRegisterStudentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<StudentDTO> {
        const response = await this.studentControllerRegisterStudentRaw(
            requestParameters,
            initOverrides
        );
        return await response.value();
    }
}
