/* tslint:disable */
/* eslint-disable */
/**
 * EVA API
 * The EVA API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { TeacherDTO } from '../models';
import { TeacherDTOFromJSON, TeacherDTOToJSON } from '../models';

/**
 * TeacherApi - interface
 *
 * @export
 * @interface TeacherApiInterface
 */
export interface TeacherApiInterface {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeacherApiInterface
     */
    teacherControllerGetTeacherRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<TeacherDTO>>;

    /**
     */
    teacherControllerGetTeacher(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<TeacherDTO>;
}

/**
 *
 */
export class TeacherApi extends runtime.BaseAPI implements TeacherApiInterface {
    /**
     */
    async teacherControllerGetTeacherRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<TeacherDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/teacher`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            TeacherDTOFromJSON(jsonValue)
        );
    }

    /**
     */
    async teacherControllerGetTeacher(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<TeacherDTO> {
        const response = await this.teacherControllerGetTeacherRaw(initOverrides);
        return await response.value();
    }
}
