$schema: 'https://moonrepo.dev/schemas/global-project.json'
fileGroups:
    configs:
        - '*.{js,json}'
    sources:
        - 'src/**/*'
        - '**/*.{ts,tsx}'
    tests:
        - 'tests/**/*.tests.*'
        - '**/__tests__/**/*'
    assets:
        - 'assets/**/*'
        - 'images/**/*'
        - 'static/**/*'
        - '**/*.{scss,css}'
        - '**/*.mdx'

tasks:
    lint:
        command:
            - eslint

        args:
            - '.'

        deps: []

        inputs:
            - '@globs(sources)'

        type: 'node'
    prettier:
        command:
            - 'prettier'

            - '--config'
            - '@in(0)'

            - '--write'
            - '**/*.{tsx,ts}'

        inputs:
            - '/.prettierrc.json'

        type: 'node'
